# Generated by Django 2.1.4 on 2018-12-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0002_auto_20181213_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='favor',
            new_name='preference',
        ),
        migrations.AddField(
            model_name='fighter',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
