# Generated by Django 2.1.4 on 2018-12-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0003_auto_20181215_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='champion_rating',
            field=models.IntegerField(default=0),
        ),
    ]
