# Generated by Django 2.1.4 on 2018-12-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0004_auto_20181215_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='smash_id',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
