# Generated by Django 2.1.4 on 2019-09-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0008_fighter_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='banjo_and_kazooie',
            field=models.FloatField(default=5),
        ),
    ]
