# Generated by Django 2.1.4 on 2019-11-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0009_fighter_banjo_and_kazooie'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='terry',
            field=models.FloatField(default=5),
        ),
    ]
