# Generated by Django 3.0.2 on 2020-02-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0010_fighter_terry'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='byleth',
            field=models.FloatField(default=5),
        ),
    ]
